In [26]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
df = pd.read_csv("student_placement_dataset_700.csv")

In [44]:
print('Value counts for Placement_Status before encoding:')
display(df['Placement_Status'].value_counts())

Value counts for Placement_Status before encoding:

Placement_Status
0    700
Name: count, dtype: int64

In [27]:
print("First 5 Records")
df.head()

First 5 Records

,Student_ID,Gender,Age,Attendance_Percentage,CRT_Attendance_Percentage,Practice_Hours_Per_Week,Previous_Sem_CGPA,Internal_Marks,Verbal_Score,Aptitude_Score,Coding_Score,Internships_Completed,Certifications,Hackathons_Participated,Leadership_Activities,Mock_Interview_Score,Projects_Completed,Communication_Skills,Placement_Status
0,1001,Male,20,72,55,7,6.13,46,46,89,34,0,1,1,1,94,0,75,Placed
1,1002,Male,24,81,54,14,8.15,91,35,55,84,2,4,1,1,73,1,45,Placed
2,1003,Female,20,77,94,11,8.22,91,40,93,98,0,6,0,4,67,5,76,Placed
3,1004,Male,20,57,82,7,8.98,45,64,47,78,2,7,5,2,50,5,62,Placed
4,1005,Male,22,99,99,21,8.42,78,56,66,50,3,6,2,5,58,5,93,Placed

In [28]:
print("Last 5 Records")
df.tail()

Last 5 Records

,Student_ID,Gender,Age,Attendance_Percentage,CRT_Attendance_Percentage,Practice_Hours_Per_Week,Previous_Sem_CGPA,Internal_Marks,Verbal_Score,Aptitude_Score,Coding_Score,Internships_Completed,Certifications,Hackathons_Participated,Leadership_Activities,Mock_Interview_Score,Projects_Completed,Communication_Skills,Placement_Status
695,1696,Female,20,74,97,9,7.76,95,50,98,88,3,6,2,2,99,6,73,Placed
696,1697,Female,20,66,69,13,7.18,75,55,90,78,2,10,5,5,85,4,84,Placed
697,1698,Male,20,61,45,20,5.57,99,87,48,93,0,10,3,4,34,4,94,Placed
698,1699,Female,21,69,89,14,7.98,47,60,95,45,2,7,3,5,80,0,100,Placed
699,1700,Female,21,87,58,8,9.46,56,74,88,60,0,6,0,0,33,2,90,Placed

In [29]:
print("Last 5 Records")
df.tail()

Last 5 Records

,Student_ID,Gender,Age,Attendance_Percentage,CRT_Attendance_Percentage,Practice_Hours_Per_Week,Previous_Sem_CGPA,Internal_Marks,Verbal_Score,Aptitude_Score,Coding_Score,Internships_Completed,Certifications,Hackathons_Participated,Leadership_Activities,Mock_Interview_Score,Projects_Completed,Communication_Skills,Placement_Status
695,1696,Female,20,74,97,9,7.76,95,50,98,88,3,6,2,2,99,6,73,Placed
696,1697,Female,20,66,69,13,7.18,75,55,90,78,2,10,5,5,85,4,84,Placed
697,1698,Male,20,61,45,20,5.57,99,87,48,93,0,10,3,4,34,4,94,Placed
698,1699,Female,21,69,89,14,7.98,47,60,95,45,2,7,3,5,80,0,100,Placed
699,1700,Female,21,87,58,8,9.46,56,74,88,60,0,6,0,0,33,2,90,Placed

In [30]:
print("Rows and Columns")
print(df.shape)

Rows and Columns
(700, 19)

In [31]:
print(df.columns)

Index(['Student_ID', 'Gender', 'Age', 'Attendance_Percentage',
       'CRT_Attendance_Percentage', 'Practice_Hours_Per_Week',
       'Previous_Sem_CGPA', 'Internal_Marks', 'Verbal_Score', 'Aptitude_Score',
       'Coding_Score', 'Internships_Completed', 'Certifications',
       'Hackathons_Participated', 'Leadership_Activities',
       'Mock_Interview_Score', 'Projects_Completed', 'Communication_Skills',
       'Placement_Status'],
      dtype='object')

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 700 non-null    int64
 1   Gender                     700 non-null    object
 2   Age                        700 non-null    int64
 3   Attendance_Percentage      700 non-null    int64
 4   CRT_Attendance_Percentage  700 non-null    int64
 5   Practice_Hours_Per_Week    700 non-null    int64
 6   Previous_Sem_CGPA          700 non-null    float64
 7   Internal_Marks             700 non-null    int64
 8   Verbal_Score               700 non-null    int64
 9   Aptitude_Score             700 non-null    int64
 10  Coding_Score               700 non-null    int64
 11  Internships_Completed      700 non-null    int64
 12  Certifications             700 non-null    int64
 13  Hackathons_Participated    700 non-null    int64
 14  Leadership_Activities      700 non-null    int64
 15  Mock_Interview_Score       700 non-null    int64
 16  Projects_Completed         700 non-null    int64
 17  Communication_Skills       700 non-null    int64
 18  Placement_Status           700 non-null    object
dtypes: float64(1), int64(16), object(2)
memory usage: 104.0+ KB

In [33]:
df.isnull().sum()

Student_ID                   0
Gender                       0
Age                          0
Attendance_Percentage        0
CRT_Attendance_Percentage    0
Practice_Hours_Per_Week      0
Previous_Sem_CGPA            0
Internal_Marks               0
Verbal_Score                 0
Aptitude_Score               0
Coding_Score                 0
Internships_Completed        0
Certifications               0
Hackathons_Participated      0
Leadership_Activities        0
Mock_Interview_Score         0
Projects_Completed           0
Communication_Skills         0
Placement_Status             0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(0)

In [35]:
df.dtypes

Student_ID                     int64
Gender                        object
Age                            int64
Attendance_Percentage          int64
CRT_Attendance_Percentage      int64
Practice_Hours_Per_Week        int64
Previous_Sem_CGPA            float64
Internal_Marks                 int64
Verbal_Score                   int64
Aptitude_Score                 int64
Coding_Score                   int64
Internships_Completed          int64
Certifications                 int64
Hackathons_Participated        int64
Leadership_Activities          int64
Mock_Interview_Score           int64
Projects_Completed             int64
Communication_Skills           int64
Placement_Status              object
dtype: object

In [36]:
encoder = LabelEncoder()

df["Gender"] = encoder.fit_transform(df["Gender"])

In [37]:
df["Placement_Status"] = encoder.fit_transform(df["Placement_Status"])
df.head()

,Student_ID,Gender,Age,Attendance_Percentage,CRT_Attendance_Percentage,Practice_Hours_Per_Week,Previous_Sem_CGPA,Internal_Marks,Verbal_Score,Aptitude_Score,Coding_Score,Internships_Completed,Certifications,Hackathons_Participated,Leadership_Activities,Mock_Interview_Score,Projects_Completed,Communication_Skills,Placement_Status
0,1001,1,20,72,55,7,6.13,46,46,89,34,0,1,1,1,94,0,75,0
1,1002,1,24,81,54,14,8.15,91,35,55,84,2,4,1,1,73,1,45,0
2,1003,0,20,77,94,11,8.22,91,40,93,98,0,6,0,4,67,5,76,0
3,1004,1,20,57,82,7,8.98,45,64,47,78,2,7,5,2,50,5,62,0
4,1005,1,22,99,99,21,8.42,78,56,66,50,3,6,2,5,58,5,93,0

In [38]:
X = df.drop(["Student_ID", "Placement_Status"], axis=1)

y = df["Placement_Status"]
X.head()
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Placement_Status, dtype: int64

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [40]:
print(X_train.shape)
print(y_train.shape)

(560, 17)
(560,)

In [41]:
print(X_test.shape)
print(y_test.shape)

(140, 17)
(140,)

In [42]:
model = LogisticRegression(max_iter=1000)

In [43]:
model.fit(X_train, y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(0)

In [ ]:
y_pred = model.predict(X_test)
print(y_pred)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy)

In [ ]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

In [ ]:
print(classification_report(y_test, y_pred))

In [ ]:
student = X.iloc[[5]]

prediction = model.predict(student)

if prediction[0] == 1:
    print("Placed")
else:
    print("Not Placed")

In [ ]:
students = X.iloc[0:10]

predictions = model.predict(students)

print(predictions)

In [ ]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

importance.sort_values(by="Coefficient", ascending=False)

In [ ]:
with open("../Models/placement_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model Saved Successfully")

In [ ]:
with open("../Models/placement_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

print("Model Loaded Successfully")

In [ ]:
prediction = loaded_model.predict(student)

if prediction[0] == 1:
    print("Placed")
else:
    print("Not Placed")

In [ ]:
print("="*60)
print("Student Placement Prediction System")
print("Version 1 Completed Successfully")
print("="*60)